// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.attachStripeCustomerStmt, err = db.PrepareContext(ctx, attachStripeCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query AttachStripeCustomer: %w", err)
	}
	if q.countAnsweredBySessionStmt, err = db.PrepareContext(ctx, countAnsweredBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountAnsweredBySession: %w", err)
	}
	if q.createReportStmt, err = db.PrepareContext(ctx, createReport); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReport: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.finalizeReportStmt, err = db.PrepareContext(ctx, finalizeReport); err != nil {
		return nil, fmt.Errorf("error preparing query FinalizeReport: %w", err)
	}
	if q.getAllQuestionDefinitionsStmt, err = db.PrepareContext(ctx, getAllQuestionDefinitions); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllQuestionDefinitions: %w", err)
	}
	if q.getAnswersBySessionStmt, err = db.PrepareContext(ctx, getAnswersBySession); err != nil {
		return nil, fmt.Errorf("error preparing query GetAnswersBySession: %w", err)
	}
	if q.getCompletionFunnelStatsStmt, err = db.PrepareContext(ctx, getCompletionFunnelStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetCompletionFunnelStats: %w", err)
	}
	if q.getDailyRevenueStmt, err = db.PrepareContext(ctx, getDailyRevenue); err != nil {
		return nil, fmt.Errorf("error preparing query GetDailyRevenue: %w", err)
	}
	if q.getQuestionByIDStmt, err = db.PrepareContext(ctx, getQuestionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetQuestionByID: %w", err)
	}
	if q.getReportByAccessTokenStmt, err = db.PrepareContext(ctx, getReportByAccessToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetReportByAccessToken: %w", err)
	}
	if q.getReportByIDStmt, err = db.PrepareContext(ctx, getReportByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReportByID: %w", err)
	}
	if q.getReportBySessionIDStmt, err = db.PrepareContext(ctx, getReportBySessionID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReportBySessionID: %w", err)
	}
	if q.getRiskResultsByReportStmt, err = db.PrepareContext(ctx, getRiskResultsByReport); err != nil {
		return nil, fmt.Errorf("error preparing query GetRiskResultsByReport: %w", err)
	}
	if q.getRiskStatsStmt, err = db.PrepareContext(ctx, getRiskStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetRiskStats: %w", err)
	}
	if q.getScoringQuestionsStmt, err = db.PrepareContext(ctx, getScoringQuestions); err != nil {
		return nil, fmt.Errorf("error preparing query GetScoringQuestions: %w", err)
	}
	if q.getSessionByAnonTokenStmt, err = db.PrepareContext(ctx, getSessionByAnonToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByAnonToken: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getSessionByStripePIStmt, err = db.PrepareContext(ctx, getSessionByStripePI); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByStripePI: %w", err)
	}
	if q.getUnprocessedStripeEventsStmt, err = db.PrepareContext(ctx, getUnprocessedStripeEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetUnprocessedStripeEvents: %w", err)
	}
	if q.getWatchAndRedRisksStmt, err = db.PrepareContext(ctx, getWatchAndRedRisks); err != nil {
		return nil, fmt.Errorf("error preparing query GetWatchAndRedRisks: %w", err)
	}
	if q.insertRiskResultStmt, err = db.PrepareContext(ctx, insertRiskResult); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRiskResult: %w", err)
	}
	if q.listPendingReportsStmt, err = db.PrepareContext(ctx, listPendingReports); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingReports: %w", err)
	}
	if q.logEmailStmt, err = db.PrepareContext(ctx, logEmail); err != nil {
		return nil, fmt.Errorf("error preparing query LogEmail: %w", err)
	}
	if q.markEmailOpenedStmt, err = db.PrepareContext(ctx, markEmailOpened); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEmailOpened: %w", err)
	}
	if q.markSessionPaidStmt, err = db.PrepareContext(ctx, markSessionPaid); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSessionPaid: %w", err)
	}
	if q.markSessionPaymentFailedStmt, err = db.PrepareContext(ctx, markSessionPaymentFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSessionPaymentFailed: %w", err)
	}
	if q.markStripeEventFailedStmt, err = db.PrepareContext(ctx, markStripeEventFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkStripeEventFailed: %w", err)
	}
	if q.markStripeEventProcessedStmt, err = db.PrepareContext(ctx, markStripeEventProcessed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkStripeEventProcessed: %w", err)
	}
	if q.setAIHedgeStmt, err = db.PrepareContext(ctx, setAIHedge); err != nil {
		return nil, fmt.Errorf("error preparing query SetAIHedge: %w", err)
	}
	if q.setReportErrorStmt, err = db.PrepareContext(ctx, setReportError); err != nil {
		return nil, fmt.Errorf("error preparing query SetReportError: %w", err)
	}
	if q.setReportProcessingStmt, err = db.PrepareContext(ctx, setReportProcessing); err != nil {
		return nil, fmt.Errorf("error preparing query SetReportProcessing: %w", err)
	}
	if q.updateSessionContextStmt, err = db.PrepareContext(ctx, updateSessionContext); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionContext: %w", err)
	}
	if q.upsertAnswerStmt, err = db.PrepareContext(ctx, upsertAnswer); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAnswer: %w", err)
	}
	if q.upsertStripeEventStmt, err = db.PrepareContext(ctx, upsertStripeEvent); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertStripeEvent: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.attachStripeCustomerStmt != nil {
		if cerr := q.attachStripeCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing attachStripeCustomerStmt: %w", cerr)
		}
	}
	if q.countAnsweredBySessionStmt != nil {
		if cerr := q.countAnsweredBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAnsweredBySessionStmt: %w", cerr)
		}
	}
	if q.createReportStmt != nil {
		if cerr := q.createReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReportStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.finalizeReportStmt != nil {
		if cerr := q.finalizeReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing finalizeReportStmt: %w", cerr)
		}
	}
	if q.getAllQuestionDefinitionsStmt != nil {
		if cerr := q.getAllQuestionDefinitionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllQuestionDefinitionsStmt: %w", cerr)
		}
	}
	if q.getAnswersBySessionStmt != nil {
		if cerr := q.getAnswersBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAnswersBySessionStmt: %w", cerr)
		}
	}
	if q.getCompletionFunnelStatsStmt != nil {
		if cerr := q.getCompletionFunnelStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCompletionFunnelStatsStmt: %w", cerr)
		}
	}
	if q.getDailyRevenueStmt != nil {
		if cerr := q.getDailyRevenueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDailyRevenueStmt: %w", cerr)
		}
	}
	if q.getQuestionByIDStmt != nil {
		if cerr := q.getQuestionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQuestionByIDStmt: %w", cerr)
		}
	}
	if q.getReportByAccessTokenStmt != nil {
		if cerr := q.getReportByAccessTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReportByAccessTokenStmt: %w", cerr)
		}
	}
	if q.getReportByIDStmt != nil {
		if cerr := q.getReportByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReportByIDStmt: %w", cerr)
		}
	}
	if q.getReportBySessionIDStmt != nil {
		if cerr := q.getReportBySessionIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReportBySessionIDStmt: %w", cerr)
		}
	}
	if q.getRiskResultsByReportStmt != nil {
		if cerr := q.getRiskResultsByReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRiskResultsByReportStmt: %w", cerr)
		}
	}
	if q.getRiskStatsStmt != nil {
		if cerr := q.getRiskStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRiskStatsStmt: %w", cerr)
		}
	}
	if q.getScoringQuestionsStmt != nil {
		if cerr := q.getScoringQuestionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScoringQuestionsStmt: %w", cerr)
		}
	}
	if q.getSessionByAnonTokenStmt != nil {
		if cerr := q.getSessionByAnonTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByAnonTokenStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getSessionByStripePIStmt != nil {
		if cerr := q.getSessionByStripePIStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByStripePIStmt: %w", cerr)
		}
	}
	if q.getUnprocessedStripeEventsStmt != nil {
		if cerr := q.getUnprocessedStripeEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUnprocessedStripeEventsStmt: %w", cerr)
		}
	}
	if q.getWatchAndRedRisksStmt != nil {
		if cerr := q.getWatchAndRedRisksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWatchAndRedRisksStmt: %w", cerr)
		}
	}
	if q.insertRiskResultStmt != nil {
		if cerr := q.insertRiskResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRiskResultStmt: %w", cerr)
		}
	}
	if q.listPendingReportsStmt != nil {
		if cerr := q.listPendingReportsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingReportsStmt: %w", cerr)
		}
	}
	if q.logEmailStmt != nil {
		if cerr := q.logEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing logEmailStmt: %w", cerr)
		}
	}
	if q.markEmailOpenedStmt != nil {
		if cerr := q.markEmailOpenedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEmailOpenedStmt: %w", cerr)
		}
	}
	if q.markSessionPaidStmt != nil {
		if cerr := q.markSessionPaidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSessionPaidStmt: %w", cerr)
		}
	}
	if q.markSessionPaymentFailedStmt != nil {
		if cerr := q.markSessionPaymentFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSessionPaymentFailedStmt: %w", cerr)
		}
	}
	if q.markStripeEventFailedStmt != nil {
		if cerr := q.markStripeEventFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markStripeEventFailedStmt: %w", cerr)
		}
	}
	if q.markStripeEventProcessedStmt != nil {
		if cerr := q.markStripeEventProcessedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markStripeEventProcessedStmt: %w", cerr)
		}
	}
	if q.setAIHedgeStmt != nil {
		if cerr := q.setAIHedgeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setAIHedgeStmt: %w", cerr)
		}
	}
	if q.setReportErrorStmt != nil {
		if cerr := q.setReportErrorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setReportErrorStmt: %w", cerr)
		}
	}
	if q.setReportProcessingStmt != nil {
		if cerr := q.setReportProcessingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setReportProcessingStmt: %w", cerr)
		}
	}
	if q.updateSessionContextStmt != nil {
		if cerr := q.updateSessionContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionContextStmt: %w", cerr)
		}
	}
	if q.upsertAnswerStmt != nil {
		if cerr := q.upsertAnswerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAnswerStmt: %w", cerr)
		}
	}
	if q.upsertStripeEventStmt != nil {
		if cerr := q.upsertStripeEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertStripeEventStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	attachStripeCustomerStmt       *sql.Stmt
	countAnsweredBySessionStmt     *sql.Stmt
	createReportStmt               *sql.Stmt
	createSessionStmt              *sql.Stmt
	finalizeReportStmt             *sql.Stmt
	getAllQuestionDefinitionsStmt  *sql.Stmt
	getAnswersBySessionStmt        *sql.Stmt
	getCompletionFunnelStatsStmt   *sql.Stmt
	getDailyRevenueStmt            *sql.Stmt
	getQuestionByIDStmt            *sql.Stmt
	getReportByAccessTokenStmt     *sql.Stmt
	getReportByIDStmt              *sql.Stmt
	getReportBySessionIDStmt       *sql.Stmt
	getRiskResultsByReportStmt     *sql.Stmt
	getRiskStatsStmt               *sql.Stmt
	getScoringQuestionsStmt        *sql.Stmt
	getSessionByAnonTokenStmt      *sql.Stmt
	getSessionByIDStmt             *sql.Stmt
	getSessionByStripePIStmt       *sql.Stmt
	getUnprocessedStripeEventsStmt *sql.Stmt
	getWatchAndRedRisksStmt        *sql.Stmt
	insertRiskResultStmt           *sql.Stmt
	listPendingReportsStmt         *sql.Stmt
	logEmailStmt                   *sql.Stmt
	markEmailOpenedStmt            *sql.Stmt
	markSessionPaidStmt            *sql.Stmt
	markSessionPaymentFailedStmt   *sql.Stmt
	markStripeEventFailedStmt      *sql.Stmt
	markStripeEventProcessedStmt   *sql.Stmt
	setAIHedgeStmt                 *sql.Stmt
	setReportErrorStmt             *sql.Stmt
	setReportProcessingStmt        *sql.Stmt
	updateSessionContextStmt       *sql.Stmt
	upsertAnswerStmt               *sql.Stmt
	upsertStripeEventStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		attachStripeCustomerStmt:       q.attachStripeCustomerStmt,
		countAnsweredBySessionStmt:     q.countAnsweredBySessionStmt,
		createReportStmt:               q.createReportStmt,
		createSessionStmt:              q.createSessionStmt,
		finalizeReportStmt:             q.finalizeReportStmt,
		getAllQuestionDefinitionsStmt:  q.getAllQuestionDefinitionsStmt,
		getAnswersBySessionStmt:        q.getAnswersBySessionStmt,
		getCompletionFunnelStatsStmt:   q.getCompletionFunnelStatsStmt,
		getDailyRevenueStmt:            q.getDailyRevenueStmt,
		getQuestionByIDStmt:            q.getQuestionByIDStmt,
		getReportByAccessTokenStmt:     q.getReportByAccessTokenStmt,
		getReportByIDStmt:              q.getReportByIDStmt,
		getReportBySessionIDStmt:       q.getReportBySessionIDStmt,
		getRiskResultsByReportStmt:     q.getRiskResultsByReportStmt,
		getRiskStatsStmt:               q.getRiskStatsStmt,
		getScoringQuestionsStmt:        q.getScoringQuestionsStmt,
		getSessionByAnonTokenStmt:      q.getSessionByAnonTokenStmt,
		getSessionByIDStmt:             q.getSessionByIDStmt,
		getSessionByStripePIStmt:       q.getSessionByStripePIStmt,
		getUnprocessedStripeEventsStmt: q.getUnprocessedStripeEventsStmt,
		getWatchAndRedRisksStmt:        q.getWatchAndRedRisksStmt,
		insertRiskResultStmt:           q.insertRiskResultStmt,
		listPendingReportsStmt:         q.listPendingReportsStmt,
		logEmailStmt:                   q.logEmailStmt,
		markEmailOpenedStmt:            q.markEmailOpenedStmt,
		markSessionPaidStmt:            q.markSessionPaidStmt,
		markSessionPaymentFailedStmt:   q.markSessionPaymentFailedStmt,
		markStripeEventFailedStmt:      q.markStripeEventFailedStmt,
		markStripeEventProcessedStmt:   q.markStripeEventProcessedStmt,
		setAIHedgeStmt:                 q.setAIHedgeStmt,
		setReportErrorStmt:             q.setReportErrorStmt,
		setReportProcessingStmt:        q.setReportProcessingStmt,
		updateSessionContextStmt:       q.updateSessionContextStmt,
		upsertAnswerStmt:               q.upsertAnswerStmt,
		upsertStripeEventStmt:          q.upsertStripeEventStmt,
	}
}
