// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AttachStripeCustomer(ctx context.Context, arg AttachStripeCustomerParams) (Session, error)
	CountAnsweredBySession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	// ---------------------------------------------------------------------------
	// REPORTS
	// ---------------------------------------------------------------------------
	CreateReport(ctx context.Context, sessionID uuid.UUID) (Report, error)
	// =============================================================================
	// sqlc QUERIES — Asymmetric Risk Mapper
	// Run: sqlc generate  (sqlc.yaml points here)
	// =============================================================================
	// ---------------------------------------------------------------------------
	// SESSIONS
	// ---------------------------------------------------------------------------
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	FinalizeReport(ctx context.Context, arg FinalizeReportParams) (Report, error)
	// ---------------------------------------------------------------------------
	// QUESTION DEFINITIONS
	// ---------------------------------------------------------------------------
	GetAllQuestionDefinitions(ctx context.Context) ([]QuestionDefinition, error)
	GetAnswersBySession(ctx context.Context, sessionID uuid.UUID) ([]GetAnswersBySessionRow, error)
	GetCompletionFunnelStats(ctx context.Context) (GetCompletionFunnelStatsRow, error)
	GetDailyRevenue(ctx context.Context) ([]GetDailyRevenueRow, error)
	GetQuestionByID(ctx context.Context, id string) (QuestionDefinition, error)
	GetReportByAccessToken(ctx context.Context, accessToken string) (GetReportByAccessTokenRow, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (Report, error)
	GetReportBySessionID(ctx context.Context, sessionID uuid.UUID) (Report, error)
	GetRiskResultsByReport(ctx context.Context, reportID uuid.UUID) ([]RiskResult, error)
	// ---------------------------------------------------------------------------
	// ANALYTICS
	// ---------------------------------------------------------------------------
	GetRiskStats(ctx context.Context) ([]PublicRiskStat, error)
	GetScoringQuestions(ctx context.Context) ([]QuestionDefinition, error)
	GetSessionByAnonToken(ctx context.Context, anonToken string) (Session, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByStripePI(ctx context.Context, stripePaymentIntent sql.NullString) (Session, error)
	GetUnprocessedStripeEvents(ctx context.Context) ([]StripeEvent, error)
	GetWatchAndRedRisks(ctx context.Context, reportID uuid.UUID) ([]RiskResult, error)
	// ---------------------------------------------------------------------------
	// RISK RESULTS
	// ---------------------------------------------------------------------------
	InsertRiskResult(ctx context.Context, arg InsertRiskResultParams) (RiskResult, error)
	// Used by the background worker to pick up unprocessed reports.
	ListPendingReports(ctx context.Context) ([]Report, error)
	// ---------------------------------------------------------------------------
	// EMAIL LOG
	// ---------------------------------------------------------------------------
	LogEmail(ctx context.Context, arg LogEmailParams) (EmailLog, error)
	MarkEmailOpened(ctx context.Context, providerID sql.NullString) (EmailLog, error)
	MarkSessionPaid(ctx context.Context, stripePaymentIntent sql.NullString) (Session, error)
	MarkSessionPaymentFailed(ctx context.Context, stripePaymentIntent sql.NullString) (Session, error)
	MarkStripeEventFailed(ctx context.Context, arg MarkStripeEventFailedParams) (StripeEvent, error)
	MarkStripeEventProcessed(ctx context.Context, stripeEventID string) (StripeEvent, error)
	SetAIHedge(ctx context.Context, arg SetAIHedgeParams) (RiskResult, error)
	SetReportError(ctx context.Context, arg SetReportErrorParams) (Report, error)
	SetReportProcessing(ctx context.Context, id uuid.UUID) (Report, error)
	UpdateSessionContext(ctx context.Context, arg UpdateSessionContextParams) (Session, error)
	// ---------------------------------------------------------------------------
	// ANSWERS
	// ---------------------------------------------------------------------------
	UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) (Answer, error)
	// ---------------------------------------------------------------------------
	// STRIPE EVENTS
	// ---------------------------------------------------------------------------
	UpsertStripeEvent(ctx context.Context, arg UpsertStripeEventParams) (StripeEvent, error)
}

var _ Querier = (*Queries)(nil)
